include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_local_variable: warning
    dead_code: error

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - annotate_overrides
    - avoid_init_to_null
    - sort_constructors_first
    - prefer_is_empty
    - avoid_return_types_on_setters
    - avoid_unused_constructor_parameters
    - prefer_double_quotes
    - directives_ordering
    - implementation_imports
    - discarded_futures
    - unnecessary_lambdas
    - unnecessary_await_in_return
    - avoid_final_parameters
    - prefer_relative_imports
    - avoid_redundant_argument_values
    - unawaited_futures
    - unnecessary_breaks
    - sort_pub_dependencies
    - always_declare_return_types
    - type_annotate_public_apis
    - omit_obvious_local_variable_types
    - prefer_const_declarations
    - cascade_invocations
    - specify_nonobvious_local_variable_types
    - use_truncating_division
    - avoid_futureor_void

