name: flutter_notifications
description: "A new Flutter Notifications Package."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^6.0.1
  equatable: ^2.0.7
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  fluttertoast: ^8.2.12
  get_it:
  injectable:

dev_dependencies:
  build_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator:

flutter:
